### ISSUE TITLE
.

### ISSUE THREAD

**Issue by robodel00008** [PingoLH/FCHarDNet#34]
.

**Comment by robodel00008** [comment]
I changed the data_loader = get_loader("icboard").  to data_loader = get_loader(args.dataset), and the error is gone. However I am getting now another error:

Traceback (most recent call last):
  File "test.py", line 119, in <module>
    test(args)
  File "test.py", line 36, in test
    device, model, loader = init_model(args)
  File "test.py", line 21, in init_model
    test_mode=True
  File "/home/robodel/FC_Hardnet_70/FCHarDNet/ptsemseg/loader/cityscapes_loader.py", line 82, in __init__
    self.images_base = os.path.join(self.root, "leftImg8bit", self.split)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneTyp



I am trying to test on a single image. What can cause this problem?
